const WEATHER_CODES_DESCRIPTIONS: { [code: number]: string | undefined } = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Drizzle",
  55: "Drizzle",
  56: "Freezing drizzle, light intensity",
  57: "Freezing drizzle",
  61: "Slight rain",
  63: "Rain",
  65: "Heavy rain",
  66: "Freezing Rain, light intensity",
  67: "Freezing Rain",
  71: "Slight snowfall",
  73: "Snowfall",
  75: "Heavy snowfall",
  77: "Hail",
  80: "Rain shower",
  81: "Rain shower",
  82: "Violent rain shower",
  85: "Snow shower",
  86: "Heavy snow shower",
  95: "Thunderstorm",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
};

export { WEATHER_CODES_DESCRIPTIONS };
